use ::phf::phf_map;
use regex::Regex;
use std::error::Error;
use std::fs;
use std::fs::File;
use std::process;

static COMP_TO_BINARY: phf::Map<&'static str, &'static str> = phf_map! {
    // a=0
    "0" => "0101010",
    "1" => "0111111",
    "-1" => "0111010",
    "D" => "0001100",
    "A" => "0110000",
    "!D" => "0001101",
    "!A" => "0110001",
    "-D" => "0001111",
    "-A" => "0110011",
    "D+1" => "0011111",
    "A+1" => "0110111",
    "D-1" => "0001110",
    "A-1" => "0110010",
    "D+A" => "0000010",
    "D-A" => "0010011",
    "A-D" => "0000111",
    "D&A" => "0000000",
    "D|A" => "0010101",
    // a=1
    "M" => "1110000",
    "!M" => "1110001",
    "-M" => "1110011",
    "M+1" => "1110111",
    "M-1" => "1110010",
    "D+M" => "1000010",
    "D-M" => "1010011",
    "M-D" => "1000111",
    "D&M" => "1000000",
    "D|M" => "1010101",
};

static DEST_TO_BINARY: phf::Map<&'static str, &'static str> = phf_map! {
    "null" => "000",
    "M" => "001",
    "D" => "010",
    "MD" => "011",
    "A" => "100",
    "AM" => "101",
    "AD" => "110",
    "AMD" => "111",
};

static JUMP_TO_BINARY: phf::Map<&'static str, &'static str> = phf_map! {
    "null" => "000",
    "JGT" => "001",
    "JEQ" => "010",
    "JGE" => "011",
    "JLT" => "100",
    "JNE" => "101",
    "JLE" => "110",
    "JMP" => "111",
};
// use std::str::Lines;

// stack variables as parameters are copied and put on the stack because they are so cheap
// heap variables are not, which is why compilation errors will be raised
//
// Allocated memory needs to have one, and only one owner (exceptions but this is generally the
// rule)
//
// Borrow with &, memory ownership will be borrowed for the procedure call
//
// Strings are always on the heap
// &str is a pointer... to either stack or heap
//
// You can have multiple references, (read only pointers) to memory as long as the owner does not
// change before the references are used
//
// #[derive(Clone)] macro for adding clone trait to allow struct to be cloned
// e.g.
// #[derive(Debug, Clone)]
// struct MyStruct {
//   a: i32,
//   b: f64,
// }
//
// Prefer & if possible over Clone & Copy traits
//
// Rust Ownership & Borrowing
// Rust eliminates memory issues (null pointers, dangling pointers, data races)
// Eliminates the garbage collector
// Parallel processing is a breeze!
//
// Keep in mind stack vs heap when dealing with ownership & borrowing

// Define a collection of commands that can be parsed from file contents
// implement an iterator that can run iterate the commands
// 3 command types A_COMMAND, C_COMMAND, L_COMMAND (pseudo command)

pub struct Parser<'a> {
    commands: Vec<Command<'a>>,
}

// ACommand regex - @R?\d{1,}
// ACommand behind comment regex (/{2}.*)@R?\d{1,}
// c-instruction generated by grex
// ^(?:A?M(?:D=(?:(?:A\+1|D(?:[+\-][1A]|[&|]A)|![AD]|[01])(?:;J(?:EQ|[GL][ET]|MP|NE))?|A?\-[1D](?:;J(?:EQ|[GL][ET]|MP|NE))?|[AD];J(?:EQ|[GL][ET]|MP|NE)|[AD])|=(?:(?:A\+1|D(?:[+\-][1A]|[&|]A)|![AD]|[01])(?:;J(?:EQ|[GL][ET]|MP|NE))?|A?\-[1D](?:;J(?:EQ|[GL][ET]|MP|NE))?|[AD];J(?:EQ|[GL][ET]|MP|NE)|[AD]))|AD=(?:(?:A\+1|D(?:[+\-][1A]|[&|]A)|![AD]|[01])(?:;J(?:EQ|[GL][ET]|MP|NE))?|A?\-[1D](?:;J(?:EQ|[GL][ET]|MP|NE))?|[AD];J(?:EQ|[GL][ET]|MP|NE)|[AD])|[AD]=(?:(?:A\+1|D(?:[+\-][1A]|[&|]A)|![AD]|[01])(?:;J(?:EQ|[GL][ET]|MP|NE))?|A?\-[1D](?:;J(?:EQ|[GL][ET]|MP|NE))?|[AD];J(?:EQ|[GL][ET]|MP|NE)|[AD])|(?:A\+1|D[+\-][1A]|D[&|]A|![AD]|[01])(?:;J(?:EQ|[GL][ET]|MP|NE))?|A?\-[1D](?:;J(?:EQ|[GL][ET]|MP|NE))?|[AD];J(?:EQ|[GL][ET]|MP|NE)|[AD])$

fn get_command_type(command: &str) -> Option<Command> {
    let a_command_regex = Regex::new("@.{1,}").unwrap();
    let l_command_regex = Regex::new("\\(.*\\)").unwrap();

    let is_l_command = l_command_regex.is_match(command);
    let is_a_command = a_command_regex.is_match(command);

    if is_l_command {
        Some(Command::LCommand(command))
    } else if is_a_command {
        Some(Command::ACommand(command))
    } else {
        if command.is_empty() {
            None
        } else {
            Some(Command::CCommand(command))
        }
    }
}

#[derive(Debug, Clone)]
enum Command<'a> {
    ACommand(&'a str), // address
    CCommand(&'a str), // compute
    LCommand(&'a str), // pseudo
}

impl Command<'_> {
    fn command_type(&self) -> &str {
        match self {
            Command::ACommand(_val) => "ACommand",
            Command::CCommand(_val) => "CCommand",
            Command::LCommand(_val) => "LCommand",
        }
    }

    fn symbol(&self) -> Option<&str> {
        match self {
            Command::ACommand(val) => Some(val),
            Command::LCommand(val) => Some(val),
            Command::CCommand(_val) => None,
        }
    }

    // dest=comp;jump
    fn dest(&self) -> Option<&str> {
        match self {
            Command::ACommand(_val) => None,
            Command::LCommand(_val) => None,
            Command::CCommand(val) => {
                let idx = val.find('=');
                match idx {
                    Some(idx) => {
                        let comp = &val[0..idx];
                        Some(comp)
                    }
                    None => None,
                }
            }
        }
    }

    fn comp(&self) -> Option<&str> {
        match self {
            Command::ACommand(_val) => None,
            Command::LCommand(_val) => None,
            Command::CCommand(val) => {
                let mut start_bytes = val.find('=').unwrap_or(0);
                if start_bytes > 0 {
                    start_bytes += 1;
                }

                let end_bytes = val.find(';').unwrap_or(val.len());
                Some(&val[start_bytes..end_bytes])
            }
        }
    }

    fn jump(&self) -> Option<&str> {
        match self {
            Command::ACommand(_val) => None,
            Command::LCommand(_val) => None,
            Command::CCommand(val) => {
                let mut start_bytes = val.find(';').unwrap_or(0);
                if start_bytes == 0 {
                    return None;
                }
                start_bytes += 1;
                Some(&val[start_bytes..])
            }
        }
    }

    fn command_as_binary(&self) -> Option<String> {
        match self {
            Command::ACommand(val) => {
                let num = &val[1..].parse::<i32>().unwrap();
                let num_as_binary = format!("0{:015b}", num);
                Some(num_as_binary)
            }
            Command::LCommand(_val) => None,
            Command::CCommand(val) => {
                let bdest = Command::bdest(self.dest());
                let bcomp = Command::bcomp(self.comp());
                let bjump = Command::bjump(self.jump());
                let num_as_binary = format!("111{}{}{}", bcomp, bdest, bjump);
                println!("Binary: {:?}", num_as_binary);
                Some(num_as_binary)
            }
        }
    }

    // dest as string representation of binary
    fn bdest(mnemonic: Option<&str>) -> &str {
        DEST_TO_BINARY[mnemonic.unwrap_or(&"null")]
    }

    // jump as string representation of binary
    fn bjump(mnemonic: Option<&str>) -> &str {
        JUMP_TO_BINARY[mnemonic.unwrap_or(&"null")]
    }

    // comp as string representation of binary
    fn bcomp(mnemonic: Option<&str>) -> &str {
        COMP_TO_BINARY[mnemonic.unwrap()]
    }
}

pub fn parse_args(args: &[String]) -> Result<String, &str> {
    if args.len() < 2 {
        return Err("not enough arguments");
    }

    let filename = args[1].clone();

    Ok(filename)
}

pub fn run(args: &[String]) -> Result<(), Box<dyn Error>> {
    let filename = parse_args(&args).unwrap_or_else(|err| {
        println!("Problem parsing arguments: {}", err);
        process::exit(1);
    });

    let contents = fs::read_to_string(&filename).expect("no such file");

    // remove comments and whitespace, may still contain newlines
    let regex = Regex::new("\n{2,}|[^\\S\\r\\n]|//.*").unwrap();
    let contents = regex.replace_all(&contents, "").into_owned();

    let commands = contents
        .lines()
        .filter_map(|line| get_command_type(line))
        .collect::<Vec<Command>>();

    let parser = Parser { commands };

    let mut result = vec![];
    for i in 0..parser.commands.len() {
        result.push(parser.commands[i].command_as_binary().unwrap());
    }

    let filename_prefix = filename.split(".").collect::<Vec<&str>>()[0];
    let new_filename = format!("{}{}", filename_prefix, &".hack");

    let data = result.join("\n");

    println!("{:?}", data);
    File::create(&new_filename);
    fs::write(new_filename, data).expect("Something went wrong writing your file");

    Ok(())
}
